# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Cypress Automation

on:
  push: 
    branches: main
 

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.1.7

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.4
        with: 
          node-version: 20

      - name: Install Dependencies
        run: npm install 

      - name: Run Cypress Test
        run: npx cypress run
        
      

  
